### ISSUE TITLE
Error when running apitest demo

### ISSUE THREAD

**Issue by raulcabero** [zatosource/zato-apitest#27] opened 2015-05-06 17:29 UTC
When I ran the apitest demo I got the following error (see below)  I am using ubuntu 14.04 and I ran all these commands to install zato-apitest 

$ sudo apt-get update && sudo apt-get upgrade
$ sudo apt-get install python-pip postgresql-server-dev-all
$ sudo apt-get install python-dev libxml2-dev libxslt1-dev
$ sudo pip install --upgrade pip

$ sudo pip install zato-apitest

Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/zato/apitest/steps/common.py", line 87, in when_the_url_is_invoked
          ctx.zato.response.data_impl = json.loads(ctx.zato.response.data.text)
        File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
          return _default_decoder.decode(s)
        File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
          raise ValueError("No JSON object could be decoded")
      ValueError: No JSON object could be decoded
      
      Captured logging:
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): apitest-demo.zato.io

Please help

**Comment by dsuch** [comment] 2015-05-06 18:15
Hello @raulcabero  - I have just tried it on a fresh Ubuntu 14.04 64-bit and I cannot reproduce it. How do you invoke the demo?

```
$ apitest demo
Creating directory `/tmp/0bc084d97d4f40bd86de6ca7471bafc4`.
OK, initialized.
Feature: zato-apitest demonstration

  Scenario: *** REST JSON Demo *** 
    Given address "http://apitest-demo.zato.io"
    Given URL path "/demo/json3"
    Given query string "?demo=1"
    Given format "JSON"
    Given header "X-Custom-Header" "MyValue"
    Given request is "{}"
    Given JSON Pointer "/a" in request is "abc"
    Given JSON Pointer "/foo" in request is an integer "7"
    Given JSON Pointer "/bar" in request is a list "1,2,3,4,5"
    Given JSON Pointer "/baz" in request is a random string
    Given JSON Pointer "/hi5" in request is one of "a,b,c,d,e"
    When the URL is invoked
    Then JSON Pointer "/action/msg" is "Now, is that cool or is that cool?"
    And JSON Pointer "/action/code" is an integer "0"
    And JSON Pointer "/action/flow" is a list "Ack,Done"
    And status is "200"
    And header "Connection" is "keep-alive"
    And header "Server" isn't empty
    And response is equal to "{"action":{"code":0, "msg":"Now, is that cool or is that cool?", "flow":["Ack", "Done"]}}"
    And response is equal to that from "demo.json"

  Scenario: *** XML/SOAP Demo *** 
    Given address "http://apitest-demo.zato.io"
    Given URL path "/demo/xml"
    Given query string "?demo=1"
    Given SOAP action "demo:xml"
    Given format "XML"
    Given namespace prefix "demo" of "http://example.com/demo"
    Given request "demo.xml"
    Given XPath "//howdy" in request is "partner"
    Given XPath "//hello" in request is a random string
    Given XPath "//world" in request is a random integer
    Given XPath "//and-beyond" in request is one of "Arcturus, Ανδρομέδα, ほうおう座"
    When the URL is invoked
    Then XPath "//demo:action/demo:code" is an integer "0"
    And XPath "//demo:action/demo:msg" is "Now, is that cool or is that cool?"

1 feature passed, 0 failed, 0 skipped
2 scenarios passed, 0 failed, 0 skipped
34 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.446s
$ 
```

**Comment by raulcabero** [comment] 2015-05-06 18:29
Hello I used the command  "apitest demo" , am I missing to install any prerequisite?

**Comment by dsuch** [comment] 2015-05-07 10:46
Can you please the full output from running ```apitest demo``` from the moment you run the command up to the exception? Thanks!

**Comment by raulcabero** [comment] 2015-05-07 13:02
Sure

```java
$ apitest demo
Creating directory `/tmp/accd2aeb2b224a23923ce9557ed53ade`.
OK, initialized.
Feature: zato-apitest demonstration

  Scenario: *** REST JSON Demo *** 
    Given address "http://apitest-demo.zato.io"
    Given URL path "/demo/json3"
    Given query string "?demo=1"
    Given format "JSON"
    Given header "X-Custom-Header" "MyValue"
    Given request is "{}"
    Given JSON Pointer "/a" in request is "abc"
    Given JSON Pointer "/foo" in request is an integer "7"
    Given JSON Pointer "/bar" in request is a list "1,2,3,4,5"
    Given JSON Pointer "/baz" in request is a random string
    Given JSON Pointer "/hi5" in request is one of "a,b,c,d,e"
    When the URL is invoked
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/zato/apitest/steps/common.py", line 87, in when_the_url_is_invoked
          ctx.zato.response.data_impl = json.loads(ctx.zato.response.data.text)
        File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
          return _default_decoder.decode(s)
        File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
          raise ValueError("No JSON object could be decoded")
      ValueError: No JSON object could be decoded
      
      Captured logging:
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): apitest-demo.zato.io

    Then JSON Pointer "/action/msg" is "Now, is that cool or is that cool?"
    And JSON Pointer "/action/code" is an integer "0"
    And JSON Pointer "/action/flow" is a list "Ack,Done"
    And status is "200"
    And header "Connection" is "keep-alive"
    And header "Server" isn't empty
    And response is equal to "{"action":{"code":0, "msg":"Now, is that cool or is that cool?", "flow":["Ack", "Done"]}}"
    And response is equal to that from "demo.json"

  Scenario: *** XML/SOAP Demo *** 
    Given address "http://apitest-demo.zato.io"
    Given URL path "/demo/xml"
    Given query string "?demo=1"
    Given SOAP action "demo:xml"
    Given format "XML"
    Given namespace prefix "demo" of "http://example.com/demo"
    Given request "demo.xml"
    Given XPath "//howdy" in request is "partner"
    Given XPath "//hello" in request is a random string
    Given XPath "//world" in request is a random integer
    Given XPath "//and-beyond" in request is one of "Arcturus, Ανδρομέδα, ほうお    Given XPath "//and-beyond" in request is one of "Arcturus, Ανδρομέδα, ほうおう座"
    When the URL is invoked
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/zato/apitest/steps/common.py", line 84, in when_the_url_is_invoked
          ctx.zato.response.data_impl = etree.fromstring(ctx.zato.response.data.text.encode('utf-8'))
        File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
        File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
        File "parser.pxi", line 1674, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101299)
        File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:96481)
        File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
        File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
        File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91772)
      XMLSyntaxError: Opening and ending tag mismatch: meta line 3 and head, line 109, column 8
      
      Captured logging:
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): apitest-demo.zato.io

    Then XPath "//demo:action/demo:code" is an integer "0"
    And XPath "//demo:action/demo:msg" is "Now, is that cool or is that cool?"


Failing scenarios:
  ../../tmp/accd2aeb2b224a23923ce9557ed53ade/features/demo.feature:4  *** REST JSON Demo ***
  ../../tmp/accd2aeb2b224a23923ce9557ed53ade/features/demo.feature:33  *** XML/SOAP Demo ***

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 2 failed, 0 skipped
22 steps passed, 2 failed, 10 skipped, 0 undefined
Took 0m4.720s
```

**Comment by dsuch** [comment] 2015-05-07 13:05
Are you sure you able to reach the address of http://apitest-demo.zato.io? I cannot find any trace of your request in the server's logs. Can you confirm you are not blocked by any sort of proxy?

**Comment by raulcabero** [comment] 2015-05-07 13:14
Hello,

I am able to reach the address, also I can get response from the REST service using curl 

```java
$ curl http://apitest-demo.zato.io/demo/json3
{
 "action":{
  "code":0,
  "msg":"Now, is that cool or is that cool?",
  "flow":["Ack", "Done"]
 }
}
```

**Comment by dsuch** [comment] 2015-05-07 13:46
Hm.. can you trace it using tcpdump or Wireshark?

I'm 100% sure your requests don't reach to the server - I can see your curl invocations + visits from the browser but not from apitest.

It really looks like something is interfering with the communications in between apitest and the server.

**Comment by raulcabero** [comment] 2015-05-08 16:37
You are right the problem is the lack of communication, I tried with my internal REST services and they worked fine, I am still investigating  why I cannot reach your severs ,but I think this issue can be closed thank you very much for the help.

**Comment by dsuch** [comment] 2015-09-04 17:53
Hi @raulcabero - seeing as it appears to be an internal networking issue I will be closing the ticket. Feel free to re-open if needed. Thanks a lot :)

**Closed by dsuch** 2015-09-04 17:53 UTC
